- name: Check whether this role supports the target OS
  ansible.builtin.assert:
    success_msg: This role supports {{ ansible_distribution }}
    fail_msg: This role does not support {{ ansible_distribution }}
    that:
      - ansible_system == 'Linux'
      - |
        ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'Fedora'

- name: Install Docker (Debian/Ubuntu)
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Docker (Fedora)
  ansible.builtin.include_tasks:
    file: fedora.yml
  when: ansible_distribution == 'Fedora'
